[package]
name = "simplechain"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
ethnum = "1.5.1"
hex = "0.4.3"
markov_namegen = "0.6.0"
rand = "0.9.1"
sha3 = "0.10.8"
sled = "0.34.7"
